Zephyr blog
softserveinc-rnd/blog pull request #4
Opened 2020-10-08 09:53 UTC by Myralllka

- typo fixes
- grammar fixes
- remove deprecated info
- add text formatting
- add code formatting

2020-10-08 10:16 UTC, tkurnyt approved these changes

2020-10-15 07:43 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  6. Zephyr support and updates.
```suggestion
6. **Zephyr support and updates.**
```

2020-10-15 07:43 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  5. Sensor support
```suggestion
5. **Sensor support**
```

2020-10-15 07:44 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  4.  Communication interfaces and device drivers
```suggestion
4.  **Communication interfaces and device drivers**
```

2020-10-15 07:44 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  3. Build toolchain
```suggestion
3. **Build toolchain**
```

2020-10-15 07:45 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  1. Supported boards
```suggestion
1. **Supported boards**
```

2020-10-15 07:46 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  2. Scalability
```suggestion
2. **Scalability**
```

2020-10-15 07:53 UTC, abench-softserve requested changes

2020-10-15 07:53 UTC, abench-softserve commented on Zephyr_RTOS/Zephyr_intro.md
>  6. Zephyr support and updates.
Use Bold for unique item names

2020-10-15 07:55 UTC, merged

2020-10-15 07:55 UTC, abench-softserve commented
Changes were approved by author. I am merging this pull request into master.